version: '3.9'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - ${JANUS_PROXY_PORT:-80}:80
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./tools/docker/nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - ./tools/docker/nginx-proxy/proxy.conf:/etc/nginx/proxy.conf:ro
      - ${JANUS_NGINX_PROXY_CERTS:-/usr/local/etc/nginx/certs}:/usr/local/etc/nginx/
      - ${JANUS_DOCKER_SOCK:-/var/run/docker.sock}:/tmp/docker.sock:ro
